name: Build Tachiyomi Extension

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Make Gradle executable
        run: chmod +x ./gradlew

      - name: Build AsuraScans extension
        run: ./gradlew :asurascans:assembleDebug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: AsuraScans-APK
          path: asurascans/build/outputs/apk/debug/*.apk
